# -*- eval: (cargo-minor-mode 1) -*-

[workspace]
members = [".", "./benchmarks"]

[package]
name = "aatree"
version = "0.1.0"
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"
license = "Apache-2.0"

[features]
default = ["log"]

[dependencies]
log = { version = "0.4.8", optional = true }
